diff --git a/Makefile b/Makefile
index b1097c7..f0d27d2 100644
--- a/Makefile
+++ b/Makefile
@@ -11,8 +11,6 @@
 # use make all and mak install to install the library 
 # You can change the install directory by editing the LIBDIR line
 #
-PREFIX=/usr/local
-
 # Library parameters
 # where to put the lib
 LIBDIR=$(PREFIX)/lib
@@ -23,17 +21,8 @@ LIBNAME_RFN=$(LIB_RFN).so.1.0
 
 HEADER_DIR=${PREFIX}/include/RF24Network
 
-# Detect the Raspberry Pi from cpuinfo
-#Count the matches for BCM2708 or BCM2709 in cpuinfo
-RPI=$(shell cat /proc/cpuinfo | grep Hardware | grep -c BCM2708)
-ifneq "${RPI}" "1"
-RPI=$(shell cat /proc/cpuinfo | grep Hardware | grep -c BCM2709)
-endif
 
-ifeq "$(RPI)" "1"
-# The recommended compiler flags for the Raspberry Pi
-CCFLAGS=-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -std=c++0x
-endif
+CXXFLAGS=-std=c++11
 
 # make all
 # reinstall the library after each recompilation
@@ -41,11 +30,11 @@ all: librf24network
 
 # Make the library
 librf24network: RF24Network.o
-	g++ -shared -Wl,-soname,$@.so.1 ${CCFLAGS} -o ${LIBNAME_RFN} $^ -lrf24-bcm
+	$(CXX) -shared -Wl,-soname,$@.so.1 ${CXXFLAGS} -o ${LIBNAME_RFN} $^ -lrf24-bcm
 
 # Library parts
 RF24Network.o: RF24Network.cpp
-	g++ -Wall -fPIC ${CCFLAGS} -c $^
+	$(CXX) -Wall -fPIC ${CXXFLAGS} -c $^
 
 # clear build files
 clean:
