diff --git a/Makefile b/Makefile
index 2090569..0e834ec 100644
--- a/Makefile
+++ b/Makefile
@@ -10,7 +10,6 @@
 # use make all and make install to install the library 
 # You can change the install directory by editing the LIBDIR line
 #
-PREFIX=/usr/local
 
 # Library parameters
 # where to put the lib
@@ -24,15 +23,6 @@ HEADER_DIR=${PREFIX}/include/RF24Mesh
 
 # Detect the Raspberry Pi from cpuinfo
 #Count the matches for BCM2708 or BCM2709 in cpuinfo
-RPI=$(shell cat /proc/cpuinfo | grep Hardware | grep -c BCM2708)
-ifneq "${RPI}" "1"
-RPI=$(shell cat /proc/cpuinfo | grep Hardware | grep -c BCM2709)
-endif
-
-ifeq "$(RPI)" "1"
-# The recommended compiler flags for the Raspberry Pi
-CCFLAGS=-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -std=c++0x
-endif
 
 # make all
 # reinstall the library after each recompilation
@@ -40,11 +30,11 @@ all: librf24mesh
 
 # Make the library
 librf24mesh: RF24Mesh.o
-	g++ -shared -Wl,-soname,$@.so.1 ${CCFLAGS} -o ${LIBNAME_RFN} $^ 
+	$(CXX) -shared -Wl,-soname,$@.so.1 ${CXXFLAGS} -o ${LIBNAME_RFN} $^ 
 
 # Library parts
 RF24Mesh.o: RF24Mesh.cpp
-	g++ -Wall -fPIC ${CCFLAGS} -c $^
+	$(CXX) -Wall -fPIC ${CXXFLAGS} -c $^
 
 # clear build files
 clean:
