diff --git a/Makefile b/Makefile
index ca5dfe8..5a85274 100644
--- a/Makefile
+++ b/Makefile
@@ -11,10 +11,9 @@
 # use make all and make install to install the examples
 # You can change the install directory by editing the prefix line
 #
-prefix := /usr/local
 
 # The recommended compiler flags for the Raspberry Pi
-CCFLAGS=-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -std=c++0x
+CXXFLAGS=-std=c++11
 
 # The needed libraries
 LIBS=-lrf24-bcm -lrf24network -lboost_thread -lboost_system
@@ -26,7 +25,7 @@ SOURCES = rf24totun.cpp
 all: ${PROGRAMS}
 
 ${PROGRAMS}: ${SOURCES}
-	g++ ${CCFLAGS} -W -pedantic -Wall ${LIBS} $@.cpp -o $@
+	$(CXX) ${CXXFLAGS} -W -std=c++11 -pedantic -Wall ${LIBS} $@.cpp -o $@
 
 clean:
 	rm -rf $(PROGRAMS)
