diff --git a/RPi/RF24Network/Makefile b/RPi/RF24Network/Makefile
index 0fefb22..e4a0492 100644
--- a/RPi/RF24Network/Makefile
+++ b/RPi/RF24Network/Makefile
@@ -11,7 +11,6 @@
 # use make all and mak install to install the library 
 # You can change the install directory by editing the LIBDIR line
 #
-PREFIX=/usr/local
 
 # Library parameters
 # where to put the lib
@@ -24,7 +23,6 @@ LIBNAME_RFN=$(LIB_RFN).so.1.0
 HEADER_DIR=${PREFIX}/include/RF24Network
 
 # The recommended compiler flags for the Raspberry Pi
-CCFLAGS=-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s
 
 # make all
 # reinstall the library after each recompilation
@@ -32,11 +30,11 @@ all: librf24network
 
 # Make the library
 librf24network: RF24Network.o
-	g++ -shared -Wl,-soname,$@.so.1 ${CCFLAGS} -o ${LIBNAME_RFN} $^ -lrf24-bcm
+	$(CXX) -shared -Wl,-soname,$@.so.1 ${CXXFLAGS} -o ${LIBNAME_RFN} $^ -lrf24-bcm
 
 # Library parts
 RF24Network.o: RF24Network.cpp
-	g++ -Wall -fPIC ${CCFLAGS} -c $^
+	$(CXX) -Wall -fPIC ${CXXFLAGS} -c $^
 
 # clear build files
 clean:
